import type { PricingData, UseCase } from "./types";

const ALL_USE_CASES: UseCase[] = [
  "coding",
  "writing",
  "data",
  "research",
  "mixed",
];

export const pricingData: PricingData = {
  tools: {
    cursor: {
      toolId: "cursor",
      displayName: "Cursor",
      category: "coding",
      alternatives: ["copilot", "windsurf"],
      plans: [
        {
          id: "cursor_free",
          name: "Hobby (Free)",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 0,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://www.cursor.com/pricing",
          isFreeTier: true,
        },
        {
          id: "cursor_pro",
          name: "Pro",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 20,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://www.cursor.com/pricing",
        },
        {
          id: "cursor_pro_plus",
          name: "Pro+",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 60,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://www.cursor.com/pricing",
        },
        {
          id: "cursor_ultra",
          name: "Ultra",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 200,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://www.cursor.com/pricing",
        },
        {
          id: "cursor_teams",
          name: "Teams",
          planType: "subscription",
          costModel: "seat",
          currency: "USD",
          monthlyPerSeat: 40,
          minSeats: 2,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://www.cursor.com/pricing",
        },
      ],
    },
    copilot: {
      toolId: "copilot",
      displayName: "GitHub Copilot",
      category: "coding",
      alternatives: ["cursor", "windsurf"],
      plans: [
        {
          id: "copilot_free",
          name: "Free",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 0,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://github.com/features/copilot/plans",
          isFreeTier: true,
        },
        {
          id: "copilot_pro",
          name: "Pro",
          planType: "subscription",
          costModel: "seat",
          currency: "USD",
          monthlyPerSeat: 10,
          minSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://github.com/features/copilot/plans",
        },
        {
          id: "copilot_pro_plus",
          name: "Pro+",
          planType: "subscription",
          costModel: "seat",
          currency: "USD",
          monthlyPerSeat: 39,
          minSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://github.com/features/copilot/plans",
        },
      ],
    },
    windsurf: {
      toolId: "windsurf",
      displayName: "Windsurf",
      category: "coding",
      alternatives: ["cursor", "copilot"],
      plans: [
        {
          id: "windsurf_free",
          name: "Free",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 0,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://windsurf.com/pricing",
          isFreeTier: true,
        },
        {
          id: "windsurf_pro",
          name: "Pro",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 20,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://windsurf.com/pricing",
        },
        {
          id: "windsurf_max",
          name: "Max",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 200,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://windsurf.com/pricing",
        },
        {
          id: "windsurf_teams",
          name: "Teams",
          planType: "subscription",
          costModel: "seat",
          currency: "USD",
          monthlyPerSeat: 40,
          minSeats: 2,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://windsurf.com/pricing",
        },
      ],
    },
    v0: {
      toolId: "v0",
      displayName: "v0",
      category: "prototyping",
      alternatives: [],
      plans: [
        {
          id: "v0_free",
          name: "Free",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 0,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://v0.app/pricing",
          isFreeTier: true,
        },
        {
          id: "v0_team",
          name: "Team",
          planType: "subscription",
          costModel: "seat",
          currency: "USD",
          monthlyPerSeat: 30,
          minSeats: 2,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://v0.app/pricing",
        },
        {
          id: "v0_business",
          name: "Business",
          planType: "subscription",
          costModel: "seat",
          currency: "USD",
          monthlyPerSeat: 100,
          minSeats: 2,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://v0.app/pricing",
        },
      ],
    },
    chatgpt: {
      toolId: "chatgpt",
      displayName: "ChatGPT",
      category: "assistant",
      alternatives: ["claude", "gemini"],
      plans: [
        {
          id: "chatgpt_free",
          name: "Free",
          planType: "subscription",
          costModel: "flat",
          currency: "INR",
          monthlyFlat: 0,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://chatgpt.com/pricing",
          isFreeTier: true,
        },
        {
          id: "chatgpt_go",
          name: "Go",
          planType: "subscription",
          costModel: "flat",
          currency: "INR",
          monthlyFlat: 399,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://chatgpt.com/pricing",
        },
        {
          id: "chatgpt_plus",
          name: "Plus",
          planType: "subscription",
          costModel: "flat",
          currency: "INR",
          monthlyFlat: 1999,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://chatgpt.com/pricing",
        },
        {
          id: "chatgpt_pro",
          name: "Pro",
          planType: "subscription",
          costModel: "flat",
          currency: "INR",
          monthlyFlat: 10699,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://chatgpt.com/pricing",
        },
        {
          id: "chatgpt_business",
          name: "Business",
          planType: "subscription",
          costModel: "seat",
          currency: "INR",
          monthlyPerSeat: 2250,
          monthlyPerSeatAnnual: 1800,
          minSeats: 2,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://chatgpt.com/pricing",
          notes: "Annual price shown per user per month.",
        },
      ],
    },
    claude: {
      toolId: "claude",
      displayName: "Claude",
      category: "assistant",
      alternatives: ["chatgpt", "gemini"],
      plans: [
        {
          id: "claude_free",
          name: "Free",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 0,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://claude.com/pricing",
          isFreeTier: true,
        },
        {
          id: "claude_pro",
          name: "Pro",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 20,
          monthlyFlatAnnual: 17,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://claude.com/pricing",
          notes: "Annual price shown per month.",
        },
        {
          id: "claude_max",
          name: "Max",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 100,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://claude.com/pricing",
          notes: "Entry tier shown as starting price.",
        },
      ],
    },
    gemini: {
      toolId: "gemini",
      displayName: "Gemini",
      category: "assistant",
      alternatives: ["chatgpt", "claude"],
      plans: [
        {
          id: "gemini_ai_plus",
          name: "Google AI Plus",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 7.99,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://one.google.com/about/google-ai-plans?hl=en-US&gl=US",
          regionalPrices: {
            US: {
              currency: "USD",
              monthlyFlat: 7.99,
            },
            IN: {
              currency: "INR",
              monthlyFlat: 399,
            },
          },
        },
        {
          id: "gemini_ai_pro",
          name: "Google AI Pro",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 19.99,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://one.google.com/about/google-ai-plans?hl=en-US&gl=US",
          regionalPrices: {
            US: {
              currency: "USD",
              monthlyFlat: 19.99,
            },
            IN: {
              currency: "INR",
              monthlyFlat: 1950,
            },
          },
        },
        {
          id: "gemini_ai_ultra",
          name: "Google AI Ultra",
          planType: "subscription",
          costModel: "flat",
          currency: "USD",
          monthlyFlat: 249.99,
          minSeats: 1,
          maxSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://one.google.com/about/google-ai-plans?hl=en-US&gl=US",
          regionalPrices: {
            US: {
              currency: "USD",
              monthlyFlat: 249.99,
            },
            IN: {
              currency: "INR",
              monthlyFlat: 24500,
            },
          },
        },
      ],
    },
    openai_api: {
      toolId: "openai_api",
      displayName: "OpenAI API",
      category: "api",
      alternatives: ["anthropic_api"],
      plans: [
        {
          id: "openai_api_payg",
          name: "Pay-as-you-go",
          planType: "api",
          costModel: "metered",
          currency: "USD",
          minSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl: "https://openai.com/api/pricing",
          apiPricing: {
            model: "gpt-5.4",
            inputPer1MTokens: 2.5,
            outputPer1MTokens: 15,
            cachedInputPer1MTokens: 0.25,
            sourceUrl: "https://openai.com/api/pricing",
          },
        },
      ],
      creditsOptions: [
        {
          id: "openai_batch",
          name: "Batch API",
          discountPercent: 0.5,
          minMonthlySpend: 100,
          allowedUseCases: ["data", "research", "mixed"],
          sourceUrl: "https://openai.com/api/pricing",
          notes: "Batch API offers 50% discount for async workloads.",
        },
      ],
    },
    anthropic_api: {
      toolId: "anthropic_api",
      displayName: "Anthropic API",
      category: "api",
      alternatives: ["openai_api"],
      plans: [
        {
          id: "anthropic_api_payg",
          name: "Pay-as-you-go",
          planType: "api",
          costModel: "metered",
          currency: "USD",
          minSeats: 1,
          useCases: ALL_USE_CASES,
          sourceUrl:
            "https://platform.claude.com/docs/en/docs/about-claude/pricing",
          apiPricing: {
            model: "claude-sonnet-4.6",
            inputPer1MTokens: 3,
            outputPer1MTokens: 15,
            cachedInputPer1MTokens: 0.3,
            sourceUrl:
              "https://platform.claude.com/docs/en/docs/about-claude/pricing",
          },
        },
      ],
      creditsOptions: [
        {
          id: "anthropic_batch",
          name: "Batch API",
          discountPercent: 0.5,
          minMonthlySpend: 100,
          allowedUseCases: ["data", "research", "mixed"],
          sourceUrl:
            "https://platform.claude.com/docs/en/docs/about-claude/pricing",
          notes: "Batch API offers 50% discount for async workloads.",
        },
      ],
    },
  },
};
